### PR TITLE
Support PHP 7.x and PHP 8

### PR DESCRIPTION
**Pull request by zboszor**
Added changes to:
1. link with -lm, I hate to see stray unresolved symbols with ldd
2. support PHP 7.x

### CODE REVIEW

**Comment by adrianguenter** [comment]
Thank you for the contribution @zboszor.

LGTM from a cursory glance, but I'll review the changes and merge later today or tomorrow.

Funny coincidence in timing, as I had planned to test/add PHP7 support this weekend myself. :)

**Comment by zboszor** [comment]
You're welcome. Did you have time to review and test this?
It worked for me under PHP 7.0.10 and 7.1.0RC1.

**Comment by zboszor** [comment]
With the last commit, `make test` succeeds with PHP 8.

**Comment by adrolter** [comment]
@zboszor Finally merged. 🙌 I'm sorry for the insane delay, and I want to thank you for continuing to update this in the intervening time. This MR unfortunately coincided with some major life events that took me away from GitHub for a long time, and as a result, it ended up falling completely off my radar until just now when I had the sudden urge to do some housekeeping...oof.

**Comment by zboszor** [comment]
> @zboszor Finally merged. 🙌 I'm sorry for the insane delay, and I want to thank you for continuing to update this in the intervening time. This MR unfortunately coincided with some major life events that took me away from GitHub for a long time, and as a result, it ended up falling completely off my radar until just now when I had the sudden urge to do some housekeeping...oof.

No problem, thanks for merging.

**Pull request merged**
